[versions]
agp = "9.0.0"
kotlin = "2.3.0"
ksp = "2.3.5"

appcompat = "1.7.1"
camerax = "1.6.0-alpha01"
constraintlayout = "2.2.1"
coreKtx = "1.17.0"
material = "1.13.0"
zxing = "3.5.3"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }

androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
androidx-camera-video = { module = "androidx.camera:camera-video", version.ref = "camerax" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }
androidx-camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camerax" }

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }

[bundles]
camerax = [
    "androidx-camera-core",
    "androidx-camera-camera2",
    "androidx-camera-lifecycle",
    "androidx-camera-video",
    "androidx-camera-view",
    "androidx-camera-extensions",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
