package app.grapheneos.camera.ktx

import android.net.Uri
import androidxc.exifinterface.media.ExifInterface
import app.grapheneos.camera.util.getImageOrientationFromUri
import com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView

fun SubsamplingScaleImageView.fixOrientationForImage(imageUri: Uri) {
    val exifOrientation = getImageOrientationFromUri(context, imageUri)
    when (exifOrientation) {
        ExifInterface.ORIENTATION_FLIP_HORIZONTAL -> {
            scaleX = -1f
            orientation = SubsamplingScaleImageView.ORIENTATION_0
        }

        ExifInterface.ORIENTATION_FLIP_VERTICAL -> {
            scaleY = -1f
            orientation = SubsamplingScaleImageView.ORIENTATION_0
        }

        ExifInterface.ORIENTATION_TRANSVERSE -> {
            scaleX = -1f
            orientation = SubsamplingScaleImageView.ORIENTATION_270
        }

        ExifInterface.ORIENTATION_TRANSPOSE -> {
            scaleX = -1f
            orientation = SubsamplingScaleImageView.ORIENTATION_90
        }

        ExifInterface.ORIENTATION_ROTATE_90 -> {
            orientation = SubsamplingScaleImageView.ORIENTATION_90
        }

        ExifInterface.ORIENTATION_ROTATE_180 -> {
            orientation = SubsamplingScaleImageView.ORIENTATION_180
        }

        ExifInterface.ORIENTATION_ROTATE_270 -> {
            orientation = SubsamplingScaleImageView.ORIENTATION_270
        }

        // ExifInterface.ORIENTATION_NORMAL and ExifInterface.ORIENTATION_UNDEFINED
        // don't need any handling as the image would be as expected (or the orientation
        // would be unknown which is unlikely since all the images displayed in our in-app
        // gallery are generated by our camera app)
    }
}